### ISSUE TITLE
If secret is not provided, output is not set

### ISSUE THREAD

**Issue by NickLavrov** [cariad-tech/merge-queue-ci-skipper#1]
We have:

```
outputs:
  skip-check:
    description: "Skip Check (boolean)"
    value: ${{ steps.passed-checks.outputs.can-skip-checks }}
```

But that passed-checks step runs `if: inputs.secret != ''`. If `secret` is provided, the step before it with no id runs, and that `output` is not set since the passed-checks step does not run.
